services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_TEST_HOST: test
      DB_TEST_DATABASE: test
    depends_on:
      - db
      - test
    command: sh -c "composer install && php artisan migrate --database=test && ./vendor/bin/phpunit && php artisan migrate && php-fpm"

  db:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql

  test:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - test_db_data:/var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  db_data:
    driver: local
  test_db_data:
    driver: local
